language: node_js
sudo: 'false'
before_script: npm install -g polymer-cli
env:
  global:
    - secure: kWM1CJhDXbKbvEyqDEHXE1uuw8f5u4d7psFNDnGm32eyWFOa5CviuIVAkm/9nkRzlO0aIUbIKjunVB6knMWtL/4pHqCcB+P6EOGBnwzUhomgpeSgt9+7YPJgSE/K+culhgzgDbEJeK2fVTLvwrIkM1Hy/xKYg9rXutY7BpGvsftDcZcfxHstyjMlHIqxeE6+5cfzPE+18QRslVFsM+zhoVBbn36TGsQ9ImpKfmZKbwQ0wvUVAxO1Bl0Tah7064bOyOcgMP87bIKZljbIQ8LEDUAbLhg/9/0bvyJn/YOC2/sZmHE1yoY9cV/Syi84jbQ8otznQSJh/y3JGKF78KcqZPu+9Gwt7yd6CTcP57wB4eswHdnWEUK9Im22uaUP95EzdhP44/1AHpHoU6e0yRwaPXWR6gCVICoLVIyK96PJrGXpOp/yJKWIWm+ZYZSoPATpmy3H5lbpwu0HDbkpdV/086ni8ZkmKuX+d6Cw3qVf0tI8HqJ2l2VFm3OkpEg5PIc0wOeCv5YGAbEbaJ8fN93ODzfiAQl2ZwNtnVJH+19LqIPzOVBuwIHUBHXIW1V31CwrOCAobx5GNN7eY4+vTn5OOpYXwEwKlyR9k1JRcHX7Xfx3WuPuLP/h78CGsRbOlWiLZVMWbmVADQLgs4THzsSpekQDfSJc9d2Q70vhYz/+Dko=
    - secure: ZuI12AK/XkUtulUA6LDQgd3d2KyEiwvdbcBus82L2Z0tZEI2z5/9drP/UXdLFKULw/BVoX9A16LBClj4OePQZlpfaW4GGczXv15biKyi0k9MUEsWRA+jxvv9aLX/7M/kNtt53VNM/ka3TJRnhGo/hNGEPbWWU7TZqM3xglCAWOpK7mekxnZgKCJHkLCvPs6DMhpo95nLwA8Ak77KmzSsuETlc3OnGMYnbxNTZlmvLKnts/fplbbXv2txDaQyfCZosOTZyRcdp6rAwj06AaPkK9bNrkwZeBUoVil/1HnZ6PS3fjUB7u5TLvXnGaeKEzONrg7HdpfHjTQ0h1QckmHBZV3siIA0NI7YLO3dVpivYhBcZzNCQ6htQI639VhUMdpeHssnB85aXydlW+AQluHe3yGYxq+SKfNGbvRhQjIeCCg14d8KtRnynHP0iiT9OlicJwggJwVikJ4M9Bqloko+GVtDhnRrEpRGdlsEipZCzx+nM/3hak1gdQRVHMx2xm0+zJ2BRglrqocDiPpzxd/G96T9UXOc5VbWh6TcTUiie2J6UWwDS35K347cwJ8//ToeNYy67AxqZVorhMbqx0r6tWmXzu41CYuYkzdjmvGOtduXY4LLe31YwMz+qBrPwH25yGNK+PYifkKdVvzYHEWvW/Bg1GzX085VY0hA1NWpiBo=
node_js: '9'
addons:
  firefox: latest
  chrome: stable
script:
  - xvfb-run polymer test --module-resolution=node --npm
  - 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test --module-resolution=node --npm -s ''default''; fi'
dist: trusty
cache:
  directories:
    - node_modules

